run:
  deadline: 5m

issues:
  exclude-dirs:
    - vendor
    - bin
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - revive
    - predeclared

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
