{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redis-ctrl.serviceAccountName" . }}
  labels:
    app: redis-ctrl
    release: {{ .Release.Name }}
{{- end }} 