name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Cache Go modules and tools
        uses: actions/cache@v4
        id: go-cache
        with:
          path: |
            ${{ runner.tool_cache }}/go
            ${{ github.workspace }}/bin
            ${{ env.GOPATH }}/pkg/mod
            ${{ env.GOCACHE }}
          key: go-${{ runner.os }}-${{ hashFiles('go.sum') }}
          restore-keys: |
            go-${{ runner.os }}-

      - name: Download dependencies
        if: steps.go-cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Check formatting
        run: make check-fmt

      - name: Run go vet
        run: make vet

      - name: Run golangci-lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Build
        run: make docker-build

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        if: github.event_name != 'pull_request'
        run: make docker-push 